export enum ActionTypes {
    USER_LOGED_IN = "@Action/USER_LOGED_IN",
    PRODUCT_LIST = "@Action/PRODUCT_LIST",
    PRODUCT_EDIT = "@Action/PRODUCT_EDIT",
    PRODUCT_DELETED = "@Action/PRODUCT_DELETED",
    REDIRECT = "@Action/REDIRECT",
    CLEAR_REDIRECT = "@Action/CLEAR_REDIRECT",
    CATEGORIES_LOOKUP = "@Action/CATEGORIES_LOOKUP",
    PRODUCT_CATEGORIES = "@Action/PRODUCT_CATEGORIES",
    PRODUCT_ADDED_TO_CATEGORY = "@Action/PRODUCT_ADDED_TO_CATEGORY",
    PRODUCT_REMOVED_FROM_CATEGORY = "@Action/PRODUCT_REMOVED_FROM_CATEGORY",
    CATEGORY_LIST = "@Action/CATEGORY_LIST",
    CATEGORY_EDIT = "@Action/CATEGORY_EDIT",
    CATEGORY_DELETE = "@Action/CATEGORY_DELETE"
}